#+TITLE: Multivariate Event Times (=mets=)
#+STARTUP: showall
#+OPTIONS: ^:{}
#+OPTIONS: title:nil author:nil
#+PROPERTY: header-args :exports both :eval yes :results output
#+PROPERTY: header-args:R :session *R*
#+PROPERTY: header-args:R+ :colnames yes :rownames no :hlines yes

#+BEGIN_export md
<!-- badges: start -->
  [![R-CMD-check](https://github.com/kkholst/mets/workflows/R-CMD-check/badge.svg)](https://github.com/kkholst/mets/actions)
  [![coverage](https://codecov.io/github/kkholst/mets/coverage.svg?branch=master)](https://codecov.io/github/kkholst/mets?branch=master)
  [![cran](https://www.r-pkg.org/badges/version-last-release/mets)](https://CRAN.R-project.org/package=mets)
  [![cran-dl](https://cranlogs.r-pkg.org/badges/mets)](https://cranlogs.r-pkg.org/downloads/total/last-month/mets)
<!-- badges: end -->

```{r include=FALSE}
options(family="Times")
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/",
  out.width = "60%"
)
```
#+END_export


* Multivariate Event Times (=mets=) <img src=man/figures/timerrr.png align="right" height="150">

Implementation of various statistical models for multivariate
event history data <doi:10.1007/s10985-013-9244-x>. Including multivariate
cumulative incidence models <doi:10.1002/sim.6016>, and  bivariate random
effects probit models (Liability models) <doi:10.1016/j.csda.2015.01.014>.
Also contains two-stage binomial modelling that can do pairwise odds-ratio
dependence modelling based marginal logistic regression models. This is an
alternative to the alternating logistic regression approach (ALR).

** Installation
#+NAME: install
#+BEGIN_SRC R :exports both :ravel eval=FALSE
install.packages("mets")
#+END_SRC

The development version may be installed directly from github
(requires [[https://cran.r-project.org/bin/windows/Rtools/][Rtools]] on windows and [[https://cran.r-project.org/bin/macosx/tools/][development tools]] (+Xcode) for Mac OS
X):
#+BEGIN_SRC R :exports both :ravel eval=FALSE
remotes::install_github("kkholst/mets", dependencies="Suggests")
#+END_SRC
or to get development version
#+BEGIN_SRC R :exports both :ravel eval=FALSE
remotes::install_github("kkholst/mets",ref="develop")
#+END_SRC

** Citation

To cite the =mets= package please use one of the following references
#+BEGIN_QUOTE
  Thomas H. Scheike and Klaus K. Holst and Jacob B. Hjelmborg (2013).
  Estimating heritability for cause specific mortality based on twin studies.
  Lifetime Data Analysis. http://dx.doi.org/10.1007/s10985-013-9244-x
#+END_QUOTE

#+BEGIN_QUOTE
  Klaus K. Holst and Thomas H. Scheike Jacob B. Hjelmborg (2015).
  The Liability Threshold Model for Censored Twin Data.
  Computational Statistics and Data Analysis. [[http://dx.doi.org/10.1016/j.csda.2015.01.014]]
#+END_QUOTE

BibTeX:
#+BEGIN_SRC LATEX
  @Article{,
    title={Estimating heritability for cause specific mortality based on twin studies},
    author={Scheike, Thomas H. and Holst, Klaus K. and Hjelmborg, Jacob B.},
    year={2013},
    issn={1380-7870},
    journal={Lifetime Data Analysis},
    doi={10.1007/s10985-013-9244-x},
    url={http://dx.doi.org/10.1007/s10985-013-9244-x},
    publisher={Springer US},
    keywords={Cause specific hazards; Competing risks; Delayed entry;
              Left truncation; Heritability; Survival analysis},
    pages={1-24},
    language={English}
  }

  @Article{,
    title={The Liability Threshold Model for Censored Twin Data},
    author={Holst, Klaus K. and Scheike, Thomas H. and Hjelmborg, Jacob B.},
    year={2015},
    doi={10.1016/j.csda.2015.01.014},
    url={http://dx.doi.org/10.1016/j.csda.2015.01.014},
    journal={Computational Statistics and Data Analysis}
  }
#+END_SRC

** Examples

#+NAME: ex1
#+BEGIN_SRC R :exports both
  library("mets")

  data(prt) ## Prostate data example (sim)

  ## Bivariate competing risk, concordance estimates
  p33 <- bicomprisk(Event(time,status)~strata(zyg)+id(id),
                    data=prt, cause=c(2,2), return.data=1, prodlim=TRUE)

  p33dz <- p33$model$"DZ"$comp.risk
  p33mz <- p33$model$"MZ"$comp.risk

  ## Probability weights based on Aalen's additive model
  prtw <- ipw(Surv(time,status==0)~country, data=prt,
              cluster="id",weight.name="w")

  ## Marginal model (wrongly ignoring censorings)
  bpmz <- biprobit(cancer~1 + cluster(id),
                   data=subset(prt,zyg=="MZ"), eqmarg=TRUE)

  ## Extended liability model
  bpmzIPW <- biprobit(cancer~1 + cluster(id),
                      data=subset(prtw,zyg=="MZ"),
                      weight="w")
  smz <- summary(bpmzIPW)

  ## Concordance
  plot(p33mz,ylim=c(0,0.1),axes=FALSE,automar=FALSE,atrisk=FALSE,background=TRUE,background.fg="white")
  axis(2); axis(1)

  abline(h=smz$prob["Concordance",],lwd=c(2,1,1),col="darkblue")
  ## Wrong estimates:
  abline(h=summary(bpmz)$prob["Concordance",],lwd=c(2,1,1),col="lightgray", lty=2)
#+END_SRC



* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables:
# coding: utf-8
# eval: (add-hook 'after-save-hook
#        '(lambda () (org-ravel-export-to-file 'ravel-markdown)) nil t)
# my-org-buffer-local-mode: t
# eval: (defun myknit() (interactive) (save-buffer)
#        (let ((cmd (concat "R-devel --slave -e 'knitr::knit(\"" (replace-regexp-in-string "org$" "Rmd" (buffer-file-name)) "\")'")))
# 	   (shell-command-to-string cmd)))
# eval: (define-key my-org-buffer-local-mode-map (kbd "<f10>") 'myknit)
# End:
