---
title: "Estimation of Haplo-type effects for discrete TTP" 
author: Klaus Holst & Thomas Scheike
date: "`r Sys.Date()`"
output:
  knitr:::html_vignette:
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Estimation of Haplo-type effects for discrete TTP}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(mets)
```

Overview 
========


```{r}
 library(mets)
 options(warn=-1)
 set.seed(1000) # to control output in simulatins for p-values below.
 n <- 1000
 k <- 5
 theta <- 2
 data <- simClaytonOakes(n,k,theta,0.3,3)
```

The data is on has one subject per row.

* time : time of event 
* status : 1 for event and 0 for censoring 
* x : x is a binary covariate 
* cluster : cluster 



We can also make survival prediction with robust standard errors using the phreg.

```{r}
  pp <-  predict(out,data[1:20,],se=TRUE,robust=TRUE)
  plot(pp,se=TRUE,whichx=1:10)
```



Goodness of fit 
===============
```

Computational aspects
--------------------


Cluster stratified Cox models
==============================


SessionInfo
============


```{r}
sessionInfo()
```
